# Generated by Django 5.1.2 on 2024-10-20 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Unnamed agenda', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='AgendaLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('commute_info', models.TextField()),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.agenda')),
                ('arrival_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_locations', to='agenda.location')),
                ('departure_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_locations', to='agenda.location')),
            ],
            options={
                'unique_together': {('agenda', 'departure_location', 'arrival_location')},
            },
        ),
        migrations.AddField(
            model_name='agenda',
            name='locations',
            field=models.ManyToManyField(through='agenda.AgendaLocation', to='agenda.location'),
        ),
    ]
