# Generated by Django 5.1.2 on 2024-11-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_agenda_created_at_agendalocation_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='locations',
        ),
        migrations.AlterField(
            model_name='agendalocation',
            name='arrival_location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='agendalocation',
            name='departure_location',
            field=models.CharField(max_length=255),
        ),
    ]
