# Generated by Django 5.1.2 on 2024-11-04 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_remove_agenda_locations_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agendalocation',
            unique_together=set(),
        ),
    ]
