number=1, name= 南京路 , address= 上海, 上海市, 黄浦区 
number=2, name= 外滩 , address= 上海, 上海市, 黄浦区 
number=3, name= 东方明珠 , address= 上海, 上海市, 浦东新区 
number=4, name= 人民广场 , address= 上海, 上海市, 黄浦区 
number=5, name= 陆家嘴 , address= 上海, 上海市, 浦东新区 
number=6, name= 田子坊 , address= 上海, 上海市, 卢湾区 
number=7, name= 上海博物馆 , address= 上海, 上海市, 黄浦区 
number=8, name= 豫园 , address= 上海, 上海市, 黄浦区 
number=9, name= 世纪公园 , address= 上海, 上海市, 浦东新区 
number=10, name= 徐家汇 , address= 上海, 上海市, 徐汇区 
number=11, name= 静安寺 , address= 上海, 上海市, 静安区 
number=12, name= 上海图书馆 , address= 上海, 上海市, 徐汇区 
number=13, name= 长风海洋世界 , address= 上海, 上海市, 普陀区 
number=14, name= 上海迪士尼乐园 , address= 上海, 上海市, 浦东新区 
number=15, name= 华东师范大学 , address= 上海, 上海市, 闵行区 
number=16, name= 博物馆 , address= 上海, 上海市, 静安区 
number=17, name= 南翔古镇 , address= 上海, 上海市, 嘉定区 
number=18, name= 上海南站 , address= 上海, 上海市, 闵行区 
number=19, name= 上海动物园 , address= 上海, 上海市, 闵行区 
number=20, name= 松江大学城 , address= 上海, 上海市, 松江区 
number=21, name= 虹口足球场 , address= 上海, 上海市, 虹口区 
number=22, name= 上海国际会议中心 , address= 上海, 上海市, 浦东新区 
number=23, name= 梅龙镇 , address= 上海, 上海市, 黄浦区 
number=24, name= 徐家汇天主教堂 , address= 上海, 上海市, 徐汇区 
number=25, name= 真如寺 , address= 上海, 上海市, 普陀区 
number=26, name= 华东理工大学 , address= 上海, 上海市, 徐汇区 
number=27, name= 中山公园 , address= 上海, 上海市, 虹口区 
number=28, name= 上海体育场 , address= 上海, 上海市, 徐汇区 
number=29, name= 虹口公园 , address= 上海, 上海市, 虹口区 
number=30, name= 陆家嘴金融区 , address= 上海, 上海市, 浦东新区 
number=31, name= 金茂大厦 , address= 上海, 上海市, 浦东新区 
number=32, name= 上海城市规划展览馆 , address= 上海, 上海市, 黄浦区 
number=33, name= 杨浦大桥 , address= 上海, 上海市, 杨浦区 
number=34, name= 浦东国际机场 , address= 上海, 上海市, 浦东新区 
number=35, name= 东方艺术中心 , address= 上海, 上海市, 浦东新区 
number=36, name= 上海世博会博物馆 , address= 上海, 上海市, 浦东新区 
number=37, name= 静安公园 , address= 上海, 上海市, 静安区 
number=38, name= 万里长征 , address= 上海, 上海市, 松江区 
number=39, name= 安福路 , address= 上海, 上海市, 徐汇区 
number=40, name= 外滩源 , address= 上海, 上海市, 黄浦区 
number=41, name= 新华路 , address= 上海, 上海市, 普陀区 
number=42, name= 奉贤海湾 , address= 上海, 上海市, 奉贤区 
number=43, name= 人民公园 , address= 上海, 上海市, 黄浦区 
number=44, name= 博物馆 , address= 上海, 上海市, 虹口区 
number=45, name= 长宁区 , address= 上海, 上海市, 长宁区 
number=46, name= 世纪大道 , address= 上海, 上海市, 浦东新区 
number=47, name= 世纪公园 , address= 上海, 上海市, 浦东新区 
number=48, name= 静安寺 , address= 上海, 上海市, 静安区 
number=49, name= 南翔古镇 , address= 上海, 上海市, 嘉定区 
number=50, name= 阳光100 , address= 上海, 上海市, 黄浦区 
number=51, name= 新天地 , address= 上海, 上海市, 卢湾区 
number=52, name= 普陀山 , address= 上海, 上海市, 普陀区 
number=53, name= 上海图书馆 , address= 上海, 上海市, 徐汇区 
number=54, name= 静安寺 , address= 上海, 上海市, 静安区 
number=55, name= 上海大剧院 , address= 上海, 上海市, 黄浦区 
number=56, name= 上海老街 , address= 上海, 上海市, 黄浦区 
number=57, name= 天山路 , address= 上海, 上海市, 长宁区 
number=58, name= 小南国 , address= 上海, 上海市, 黄浦区 
number=59, name= 南浦大桥 , address= 上海, 上海市, 浦东新区 
number=60, name= 松江广场 , address= 上海, 上海市, 松江区 
number=61, name= 苏州河 , address= 上海, 上海市, 浦东新区 
number=62, name= 浦江游船 , address= 上海, 上海市, 浦东新区 
number=63, name= 四平路 , address= 上海, 上海市, 杨浦区 
number=64, name= 复兴公园 , address= 上海, 上海市, 徐汇区 
number=65, name= 西藏南路 , address= 上海, 上海市, 黄浦区 
number=66, name= 大宁路 , address= 上海, 上海市, 大宁区 
number=67, name= 东昌路 , address= 上海, 上海市, 浦东新区 
number=68, name= 西南地区 , address= 上海, 上海市, 徐汇区 
number=69, name= 长江大桥 , address= 上海, 上海市, 宝山区 
number=70, name= 望海路 , address= 上海, 上海市, 宝山区 
number=71, name= 云岭东路 , address= 上海, 上海市, 普陀区 
number=72, name= 黄浦江 , address= 上海, 上海市, 黄浦区 
number=73, name= 青浦区 , address= 上海, 上海市, 青浦区 
number=74, name= 华东师范大学 , address= 上海, 上海市, 闵行区 
number=75, name= 闵行区 , address= 上海, 上海市, 闵行区 
number=76, name= 南方商城 , address= 上海, 上海市, 宝山区 
number=77, name= 华东理工大学 , address= 上海, 上海市, 徐汇区 
number=78, name= 东宁路 , address= 上海, 上海市, 浦东新区 
number=79, name= 金山区 , address= 上海, 上海市, 金山区 
number=80, name= 奉贤区 , address= 上海, 上海市, 奉贤区 
number=81, name= 松江区 , address= 上海, 上海市, 松江区 
number=82, name= 上海大剧院 , address= 上海, 上海市, 黄浦区 
number=83, name= 西安路 , address= 上海, 上海市, 普陀区 
number=84, name= 天潼路 , address= 上海, 上海市, 黄浦区 
number=85, name= 虹口区 , address= 上海, 上海市, 虹口区 
number=86, name= 长宁区 , address= 上海, 上海市, 长宁区 
number=87, name= 上海南站 , address= 上海, 上海市, 闵行区 
number=88, name= 漕河泾 , address= 上海, 上海市, 徐汇区 
number=89, name= 华东理工大学 , address= 上海, 上海市, 徐汇区 
number=90, name= 中兴路 , address= 上海, 上海市, 黄浦区 
number=91, name= 浦东国际机场 , address= 上海, 上海市, 浦东新区 
number=92, name= 上海市人民医院 , address= 上海, 上海市, 黄浦区 
number=93, name= 上海中医药大学 , address= 上海, 上海市, 徐汇区 
number=94, name= 复兴路 , address= 上海, 上海市, 徐汇区 
number=95, name= 西虹口 , address= 上海, 上海市, 虹口区 
number=96, name= 长宁路 , address= 上海, 上海市, 长宁区 
number=97, name= 东平路 , address= 上海, 上海市, 浦东新区 
number=98, name= 上海北站 , address= 上海, 上海市, 闵行区 
number=99, name= 大连路 , address= 上海, 上海市, 杨浦区 
number=100, name= 黄浦滨江 , address= 上海, 上海市, 黄浦区 
